version: '3.9'

services:
  fastapp:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    image: postgres:15.3-alpine3.18
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always

volumes:
  db_volume:
