"""first migration

Revision ID: 1d111a4e443b
Revises: 
Create Date: 2023-07-02 05:47:37.262082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d111a4e443b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.Enum('FEMALE', 'MALE', name='sexoptions'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('grade', sa.Enum('DIPLOMA', 'BACHELOR', 'MASTER', 'DOCTORATE', name='gradeoptions'), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
