"""second migration

Revision ID: 821e197ead68
Revises: 1d111a4e443b
Create Date: 2023-07-02 05:52:01.751495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821e197ead68'
down_revision = '1d111a4e443b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
