"""<first migration>

Revision ID: c66ce96ff99b
Revises: 
Create Date: 2023-07-03 04:38:08.496128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66ce96ff99b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', name='genderoptions'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('grade', sa.Enum('DIPLOMA', 'BACHELOR', 'MASTER', 'DOCTORATE', name='gradeoptions'), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
